os:
  - linux
  - osx
language: node_js
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
script:
  - npm run prepublishOnly
jobs:
  include:
    - stage: npm release
      node_js: '10'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on: deploy-npm-release
